# CatBond 모델 설정 파일

# 데이터 설정
data:
  data_dir: "./data/processed/"
  rain_file: "rain_nation_daily_glm.parquet"
  loss_file: "merged_flood_data_updated.csv"
  features_file: "features.parquet"
  climate_file: "climate_idx.csv"

# 모델 설정
model:
  face_value: 100000000000 # 1,000억원 (액면가)
  cover_limit: 3000000000000 # 3조 원 (기존 호환성용)
  quantile_level: 0.999863 # 99.9863% 분위수 (연 0.05건 확률)
  p_annual: 0.000137 # 연간 0.05건 확률
  # chungju_weight: 3.0 # 충주 지역 가중치 (제거됨 - 편향 방지)
  # major_city_weight: 1.5 # 대도시 가중치 (제거됨 - 편향 방지)
  chungju_threshold: 205.0 # 충주시 트리거 임계값 (mm)

# 빈도 모델 설정
frequency:
  alpha: 0.01
  max_iter: 1000
  fit_intercept: true
  exposure_growth_rate: 0.02

# 트리거 모델 설정
trigger:
  learning_rate: 0.005
  num_leaves: 15
  max_depth: 4
  feature_fraction: 0.6
  bagging_fraction: 0.6
  bagging_freq: 5
  lambda_l2: 1.0
  lambda_l1: 0.1
  min_child_samples: 100
  min_child_weight: 0.5
  class_weight_max: 10.0
  early_stopping_rounds: 250
  num_boost_round: 3000

# 손실 모델 설정 (MLP)
severity:
  # MLP 아키텍처 설정
  hidden_units: [128, 64, 32] # 은닉층 뉴런 수
  learning_rate: 0.001 # 학습률
  epochs: 200 # 최대 에포크
  batch_size: 32 # 배치 크기
  dropout_rate: 0.3 # 드롭아웃 비율
  l2_reg: 0.01 # L2 정규화
  early_stopping_patience: 20 # 조기 종료 인내심
  classification_threshold: 0.001 # 손실률 분류 임계값 (0.1%) - F1 Score 계산용

  # 기존 LightGBM 설정 (호환성용)
  learning_rate_lgb: 0.005
  num_leaves: 15
  max_depth: 4
  feature_fraction: 0.6
  bagging_fraction: 0.6
  bagging_freq: 5
  lambda_l2: 1.0
  lambda_l1: 0.1
  min_child_samples: 100
  min_child_weight: 0.5
  early_stopping_rounds: 250
  num_boost_round: 3000

# 피처 설정
features:
  climate_features: ["ENSO", "IOD", "PDO"]
  trigger_features:
    [
      "rain_mm",
      "rain_3d_sum",
      "rain_7d_sum",
      "rain_max_last30d",
      "month_sin",
      "month_cos",
    ]
  severity_features:
    [
      "rain_mm",
      "rain_3d_sum",
      "rain_7d_sum",
      "rain_max_last30d",
      "imperv_area_m2",
      "risk_index",
      "pop_density_km2",
      "grdp",
      "sewer_length_m",
      "gov_spend",
      "month_sin",
      "month_cos",
    ]

# 학습 설정
training:
  test_size: 0.2
  random_state: 42
  n_splits: 1
  recall_threshold: 0.5
  outlier_quantile: 0.999
  # 교차검증 설정
  cv_folds: 5 # Group K-Fold 분할 수
  cv_shuffle: true # 교차검증 시 셔플 여부
  cv_selection_metric: "r2" # 최적 모델 선택 기준 (r2, mae, rmse)

# Expected Loss 설정
expected_loss:
  years: 3 # 만기 (n)
  face_value: 100000000000 # 액면가 (F) - 1,000억원
  loading_factor: 0.05 # 로딩 팩터

# 모델 저장 설정
output:
  # 기본 모델 파일들
  frequency_model: "models/catbond_frequency_model.pkl"
  trigger_model: "models/catbond_trigger_model.pkl"
  severity_model: "models/catbond_severity_model.h5" # MLP 모델은 .h5 확장자 사용
  region_info: "models/catbond_region_info.pkl"

  # 백업 및 버전 관리
  backup_dir: "models/backup/"
  version_prefix: "v1.0"

  # 결과 및 로그
  results_dir: "results/"
  logs_dir: "logs/"
